### ISSUE TITLE
Getting error User "system:anonymous" cannot list nodes at the cluster scope

### ISSUE THREAD

**Issue by chinnasamyb** [oracle/learning-library#250]
When I am running **while true; do kubectl get nodes; sleep 10; done**  on my Virtual box terminal , I am getting 

Error from server (Forbidden): nodes is forbidden: User "system:anonymous" cannot list nodes at the cluster scope

**Comment by derekoneil** [comment]
Hello,

I suspect that kubectl is not reading your kubeconfig file correctly. Can you ensure that 

1.  The KUBECONFIG environment variable is set to point to the correct file 
`echo $KUBECONFIG` should return `/home/oracle/terraform-kubernetes-installer/generated/kubeconfig`

2.   the kubeconfig file looks complete? 
`cat $KUBECONFIG` should look like this: 

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://189.213.15.223:443
  name: bmcs-k8s-cluster
contexts:
- context:
    cluster: bmcs-k8s-cluster
    user: default-admin
  name: bmcs-k8s-context
current-context: bmcs-k8s-context
kind: Config
preferences: {}
users:
- name: default-admin
  user:
    client-certificate-data: LS2tLS1CR......
    client-key-data: LS2tLS1CR........
```

**Comment by derekoneil** [comment]
It seems like kubectl is trying to use something like basic authentication instead of the client certificate for the default-admin user. Can you please share the output of `kubectl auth can-i get nodes`, `kubectl config view`, and `kubectl version`?

```
[oracle@OL74-ClientImage terraform-kubernetes-installer]$ kubectl auth can-i get nodes
yes
```

```
[oracle@OL74-ClientImage terraform-kubernetes-installer]$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://129.213.15.213:443
  name: bmcs-k8s-cluster
contexts:
- context:
    cluster: bmcs-k8s-cluster
    user: default-admin
  name: bmcs-k8s-context
current-context: bmcs-k8s-context
kind: Config
preferences: {}
users:
- name: default-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

```
[oracle@OL74-ClientImage terraform-kubernetes-installer]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6+coreos.0", GitCommit:"c2aac694c2c7373dfe3ad81f47fc3cbc70a5a8fa", GitTreeState:"clean", BuildDate:"2018-03-21T21:54:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
